import Head from 'next/head'

import {
  LandingDiscordSection,
  LandingHeader,
  LandingHeroSection,
  LandingFooter,
  LandingNftMintSection,
  LandingNftsSection,
  LandingRoadmapSection,
  LandingTeamSection,
  LandingTournamentSection,
  LandingStatsSection,
} from '@/components'

import { NextPageWithLayout } from './_app'

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Megafans.io - Esports for All!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative decoration-solid decoration-auto decoration-neon no-underline font-['Space Grotesk']">
        <LandingHeader />
        <LandingHeroSection />
        <LandingNftMintSection />
        <LandingTeamSection />
        <LandingRoadmapSection />
        <LandingNftsSection />
        <LandingTournamentSection />
        <LandingStatsSection />
        <LandingDiscordSection />
        <LandingFooter />
      </main>
    </>
  )
}

export default Page
