import { ReactElement } from 'react'
import Head from 'next/head'

import Image from 'next/image'
import { Layout, Home } from '@/components'
import { NextPageWithLayout } from './_app'

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  )
}

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <div>
      {/* Header */}
      <div className="w-100 p-4 flex items-center" style={{ borderBottom: 2, borderBottomColor: 'yellow' }}>
        <div className="flex-1">
          <Image src={'/landing/megafans-header.png'} width={400} height={150} alt="header logo" />
        </div>
        <div className="flex">
          <Image src={'/landing/discord-logo.png'} width={50} height={50} alt="header logo" />
        </div>
        <div className="flex">
          <Image src={'/landing/telegram-logo.png'} width={50} height={50} alt="header logo" />
        </div>
        <div className="flex">
          <Image src={'/landing/twitter-logo.png'} width={50} height={50} alt="header logo" />
        </div>
        <div className="flex">
          <Image src={'/landing/button.png'} width={300} height={300} alt="header logo" />
        </div>
      </div>
    </div>
  )
}

export default Page
