import { ReactElement } from 'react'
import Head from 'next/head'

import Image from 'next/image'
import { Layout, Home } from '@/components'
import { NextPageWithLayout } from './_app'

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk&display=swap" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  )
}

Page.getLayout = function getLayout(page: ReactElement) {
  return (
    <div>
      {/* Header */}
      <div className="w-100 p-3 flex items-center" style={{ borderBottom: 2, borderBottomColor: 'yellow' }}>
        <div className="flex-1">
          <Image src={'/landing/megafans-header.png'} width={400} height={150} alt="header logo" />
        </div>
        <div className="flex">
          <Image src={'/landing/discord-logo.png'} width={50} height={50} alt="header logo" />
        </div>
        <div className="flex">
          <Image src={'/landing/telegram-logo.png'} width={50} height={50} alt="header logo" />
        </div>
        <div className="flex">
          <Image src={'/landing/twitter-logo.png'} width={50} height={50} alt="header logo" />
        </div>
        <div className="flex" style={{ position: 'relative', cursor: 'pointer' }}>
          <div style={{ position: 'absolute', right: 85, top: 25 }}>
            <a
              href="https://megafans.io/wp-content/uploads/2022/06/MS-MegaFans-White-Paper-May-24-2022.pdf"
              target={'_blank'}
            >
              <p
                className="lightPaperButton"
                style={{
                  fontSize: '1.3111111111111rem',
                  fontWeight: 600,
                  lineHeight: '20px',
                  fontFamily: '"Space Grotesk", sans-serif;',
                  color: '#B7FFFD',
                  textDecorationLine: 'none',
                  textDecorationColor: '#B7FFFD',
                  textDecorationStyle: 'solid',
                  textDecorationThickness: 'auto',
                }}
              >
                LIGHT PAPER
              </p>
            </a>
          </div>
          <Image src={'/landing/button.png'} width={300} height={300} alt="header logo" />
        </div>
      </div>
      {/* FIRST IMAGE */}
      <div
        style={{
          backgroundImage: 'url(/landing/prombg.png)',
          backgroundRepeat: 'no-repeat',
          position: 'relative',
          alignSelf: 'auto',
          backgroundPositionX: '50%',
          backgroundPositionY: '100%',
          backgroundSize: 'cover',
          flexBasis: 'auto',
          flexGrow: 0,
          flexShrink: 1,
          height: '929px',
        }}
      >
        <div
          style={{
            backgroundImage: 'url(/landing/characters.png)',
            backgroundPositionX: '50%',
            backgroundPositionY: 0,
            backgroundSize: 'contain',
            backgroundRepeat: 'no-repeat',
            position: 'absolute',
            height: '929px',
            bottom: 0,
            lineHeight: '33.4286px',
            left: '125px',
            width: '100%',
          }}
        ></div>
        <div style={{ position: 'relative', display: 'flex', minHeight: '1px', alignSelf: 'auto' }}>
          <div
            style={{
              position: 'relative',
              alignContent: 'flex-start',
              flexWrap: 'wrap',
              paddingBottom: '170px',
              lineHeight: '33px',
              width: '100%',
            }}
          >
            {/* NFT COLLECTION */}
            <div
              style={{
                backgroundImage: 'url(/landing/banner-button.png)',
                backgroundSize: 'contain',
                backgroundRepeat: 'no-repeat',
                backgroundPositionX: '50%',
                backgroundPositionY: '50%',
                textAlign: 'center',
                padding: '36px',
                display: 'block',
              }}
            >
              <h1
                style={{
                  color: '#C7FFFD',
                  fontSize: '43px',
                  fontWeight: 600,
                  fontFamily: '"Space Grotesk", sans-serif;',
                  lineHeight: '43px',
                }}
              >
                NFT COLLECTION
              </h1>
            </div>

            {/* STAKE TO EARN */}
            <div
              style={{
                backgroundImage: 'url(/landing/light-button.png)',
                backgroundRepeat: 'no-repeat',
                backgroundPositionX: '50%',
                backgroundPositionY: '50%',
                backgroundSize: 'contain',
                padding: '17px',
                textAlign: 'center',
                display: 'block',
              }}
            >
              <p>STAKE TO EARN</p>
            </div>
          </div>
        </div>
      </div>
      {/* Second section */}
      <div
        style={{
          height: '1246px',
          padding: '10px',
          backgroundImage: 'radial-gradient(at center left, #502865 0%, #16131E 68%)',
          backgroundColor: 'transparent',
          opacity: 1,
          transition: 'background 0.3s, border-radius 0.3s, opacity 0.3s;',
        }}
      >
        <Image src={'/landing/megafans-label.png'} width={1900} height={210} />
        <div className="flex">
          <div className="flex-auto w-32 self-center" style={{ padding: '10px'}}>
            <div className='flex flex-col'>
              <h4
                style={{
                  color: 'white',
                  fontSize: '20px',
                  fontFamily: '"Space Grotesk", sans-serif;',
                  fontWeight: 600,
                  verticalAlign: 'baseline',
                  marginBottom: '100px',
                }}
              >
                MegaFans is building and supporting the world’s first esports community using blockchain products;
                Utility cryptocurrency and NFTs with a novel Stake-to-Earn + Play-to-Win environment for gamers,
                collectors, developers, and the world...
              </h4>
              <h2
                style={{
                  color: '#7DFFFB',
                  fontSize: '48px',
                  fontFamily: '"Space Grotesk", sans-serif;',
                  fontWeight: 600,
                }}
              >
                Supply : TDB
              </h2>
              <h2
                style={{
                  color: '#7DFFFB',
                  fontSize: '48px',
                  fontFamily: '"Space Grotesk", sans-serif;',
                  fontWeight: 600,
                }}
              >
                Price: TBD
              </h2>
              <div style={{ marginTop: '50px' }}>
                <div
                  style={{
                    backgroundImage: 'url(/landing/light-lightning-button.png)',
                    backgroundRepeat: 'no-repeat',
                    backgroundPositionY: '50%',
                    backgroundSize: 'contain',
                    lineHeight: '33px',
                    textAlign: 'center',
                    paddingLeft: '65px',
                    paddingRight: '65px',
                    paddingTop: '45px',
                    paddingBottom: '45px',
                    width: '275px',
                  }}
                >
                  <span
                    style={{
                      cursor: 'pointer',
                      color: '#1e293b',
                      lineHeight: '20px',
                      fontFamily: '"Space Grotesk", sans-serif;',
                      fontSize: '20px',
                      fontWeight: 600,
                    }}
                  >
                    AUTO-STAKED
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div className="flex-auto w-32" style={{ padding: '10px' }}>
            <Image src={'/landing/lady.png'} width={820} height={876} />
          </div>
        </div>
      </div>

      {/* NFT MINT SECTION */}
      <div
        style={{
          height: '916px',
          backgroundImage: 'radial-gradient(at center right, #502865 0%, #16131E 68%)',
          backgroundColor: '#16131E',
          opacity: 1,
          transition: 'background 0.3s, border-radius 0.3s, opacity 0.3s;',
        }}
      >
        <div className="flex flex-col">
          <div style={{ marginBottom: '20px' }}>
            <p
              className="text-center"
              style={{
                color: '#C7FFFD',
                fontSize: '48px',
                fontWeight: 600,
                lineHeight: '48px',
                fontFamily: '"Space Grotesk", sans-serif;',
              }}
            >
              NFT MINT
            </p>
          </div>
          <div style={{ marginBottom: '20px' }}>
            <p
              className="text-center"
              style={{
                color: '#C7FFFD',
                fontSize: '32px',
                fontWeight: 600,
                lineHeight: '32px',
                fontFamily: '"Space Grotesk", sans-serif;',
              }}
            >
              ETHEREUM
            </p>
          </div>
          <div>
            <p
              className="text-center"
              style={{
                color: '#C7FFFD',
                fontSize: '18px',
                fontWeight: 600,
                lineHeight: '33px',
                fontFamily: '"Space Grotesk", sans-serif;',
              }}
            >
              Available To Open Sea
            </p>
          </div>
        </div>

        {/* ETH WITH GUNS IMAGES */}
        <div className="flex">
          {/* LEFT GUN */}
          <div>
            <Image src={'/landing/leftgun.png'} height={186} width={208} />
          </div>
          {/* ETHEREUM */}
          <div>
            <Image src={'/landing/ethereum.png'} height={481} width={650} />
          </div>
          {/* RIGHT GUN */}
          <div>
            <Image src={'/landing/rightgun.png'} height={186} width={208} />
          </div>
        </div>

        {/* BUTTONS */}
        <div>
          <div>Light paper</div>
          <div>Starts on</div>
        </div>
      </div>
    </div>
  )
}

export default Page
