import { ReactElement } from 'react'
import { GetStaticProps } from 'next'
import Head from 'next/head'

import { useMounted } from '@/hooks'
import { Layout, Profile } from '@/components'
import { NextPageWithLayout } from './_app'

const Page: NextPageWithLayout = () => {
  const mounted = useMounted()

  return (
    <>
      <Head>
        <title>MegaFans.io - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {mounted && <Profile />}
    </>
  )
}

Page.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>
}

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      protected: false,
    },
  }
}

export default Page
